version: '3.1'

services:

  db:
    image: mysql:8.0.15
    command: ["--default-authentication-plugin=mysql_native_password", "--log_bin_trust_function_creators=1"]
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: 'local-root-password'
       MYSQL_DATABASE: 'local-db'
       MYSQL_USER: 'local-user'
       MYSQL_PASSWORD: 'local-password'
       TZ: 'Asia/Jakarta'
    ports:
      - 3306:3306